version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 9432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: db
    volumes:
      - data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    restart: always
    ports:
      - 9080:8080
    volumes:
      - "./hasura/metadata:/hasura-metadata"
      - "./hasura/migrations:/hasura-migrations"
      - "./hasura/seeds:/hasura-seeds"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@postgres/${PG_DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:0.22.18
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      CONFIGURATION_STORAGE_TYPE: etcd
      CONFIGURATION_STORAGE_URL: http://etcd:2379
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      STANDALONE_MODE: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"

  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      SCHEMA_PROVIDER_URL: etcd:2379
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: "false"
    image: semitechnologies/contextionary:en0.16.0-v0.4.19
    ports:
      - 9999:9999
  etcd:
    command:
      - --name
      - s1
      - --data-dir
      - /etcd-data
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-advertise-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - s1=http://0.0.0.0:2380
      - --initial-cluster-token
      - tkn
      - --initial-cluster-state
      - new
    entrypoint: /usr/local/bin/etcd
    image: gcr.io/etcd-development/etcd:v3.3.8
    ports:
      - 2379:2379

volumes:
  data:
